services:
# ─────────────────── BACKEND ────────────────────
  - type: web
    name: backend
    env: docker
    plan: free
    repo: https://github.com/mohdulo/BvIsOn
    branch: docker-bis
    rootDir: Server
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: DB_HOST
        value: mysql          # ← nom du service ci-dessous
      - key: DB_PORT
        value: "3306"
      - key: DB_USER
        value: mouha
      - key: DB_PASSWORD
        value: kali
      - key: DB_NAME
        value: data
      - key: DATABASE_URL
        value: mysql+pymysql://mouha:kali@mysql:3306/data
      # … autres variables (JWT, CORS, etc.) …

# ─────────────────── FRONTEND ────────────────────
  - type: web
    name: frontend
    env: docker
    plan: free
    repo: https://github.com/mohdulo/BvIsOn
    branch: docker-bis
    rootDir: Client
    dockerfilePath: ./Dockerfile
    autoDeploy: true

# ─────────────────── MYSQL PRIVATE ───────────────
  - type: private            # pas d'URL publique
    name: mysql              # ← hostname interne: mysql
    env: docker
    image: mysql:8.0
    plan: free
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: kali
      - key: MYSQL_USER
        value: mouha
      - key: MYSQL_PASSWORD
        value: kali
      - key: MYSQL_DATABASE
        value: data
